### ISSUE TITLE
Could you please provide the entire environment?

### ISSUE THREAD

**Issue by passermyh** [CodesForNlp/TTEA#1]
![image](https://github.com/CodesForNlp/TTEA/assets/71198047/54bfe4a8-4ab0-48d4-a53d-7c792db9ae40)
I'm not sure why this error occured. Maybe it's because the diff between the environments?

**Comment by CodesForNlp** [comment]
Thanks for your attention, 
1）you can change your package version ie. pytorch+cuXX，torchvision, torchaudio
2）you should check your dataset carefully
3）I will try to confirm the source of this problem.

**Comment by passermyh** [comment]
Thanks for your work and your reply!

After many attemps, I've run this code. Finally environment is as follow:
pytorch 1.8+cu102, apex-22.04-dev, torch-geometric=2.1.

By the way, I still have other questions.
1.The main results.
![image](https://github.com/CodesForNlp/TTEA/assets/71198047/1547a8f8-54f6-4151-bfde-c3549dc9146c)
![image](https://github.com/CodesForNlp/TTEA/assets/71198047/f6b41590-382a-4582-b12b-8389c98e0783)
So does the final result comes from the "Left"?
2. How could I do the ablation study(table 2)? I've got table 3.
![image](https://github.com/CodesForNlp/TTEA/assets/71198047/d9f94bdb-46df-4f78-a973-2e210cf3cea1)

**Comment by passermyh** [comment]
Thanks for your excellent work again
